version: "3"
services:
  backend:
    restart: "no"
    build: ./backend
  frontend:
    restart: "no"
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_HOST}
  webserver:
    restart: "no"
    build: ./webserver
